### ISSUE TITLE
[Bug] /api/downloads shows Completed downloads

### ISSUE THREAD

**Issue by twist3dimages** [nbr23/youtube-dl-server#102]
I think the /api/downloads endpoint is supposed to only be showing Running but it's showing completed too. Is it possible to add a filter for only running downloads?

if this is intended, should I make a feature request?

**Comment by twist3dimages** [comment]
Also it looks like the "Jobs" page only  displays 2 concurrent downloads at a time

**Comment by twist3dimages** [comment]
and even though i have about 50 downloads enabled I have 9 queued but I can't see them in the web ui

**Comment by twist3dimages** [comment]
![image](https://github.com/nbr23/youtube-dl-server/assets/33134502/523d70d8-fbf3-4bf5-858a-2d54dfa498ec)

**Comment by nbr23** [comment]
> I think the /api/downloads endpoint is supposed to only be showing Running but it's showing completed too. Is it possible to add a filter for only running downloads?
> 
> if this is intended, should I make a feature request?

Hi, yes this is intended, but I'll work on a filter sure

**Comment by nbr23** [comment]
> Also it looks like the "Jobs" page only displays 2 concurrent downloads at a time

tried to reproduce this one but was not able to. Are you sure you have 10 workers ?
I've added the worker count in the UI in the latest release (10 in the case below) just so you can make sure it's taken into account.
<img width="205" alt="image" src="https://github.com/nbr23/youtube-dl-server/assets/1313493/6edc2552-a5d1-41d7-a1d8-a6051f02f5ad">

**Comment by twist3dimages** [comment]
It looks fixed, not sure if my container was messed up
