### ISSUE TITLE
fresh install, getting a failure on everything youtube

### ISSUE THREAD

**Issue by ericblade** [nbr23/youtube-dl-server#107]
![image](https://github.com/nbr23/youtube-dl-server/assets/1451847/1151f3f7-c9ca-4095-be73-75927a4980f7)

I just replaced the original youtube-dl-server with this to try out the more advanced features, and .. nothing seems to work.  Using a fresh download directory, all stock configuration.

**Comment by nbr23** [comment]
Hi @ericblade, looks like a local issue on your end (network related?). I'm not able to reproduce and this doesn't look like a youtube-dl-server issue. Not sure I can be of much help :(

**Comment by ericblade** [comment]
Hi @nbr23 I appreciate you having a look, I reverted back to the original and that's working fine (well, as fine as it does, which considering how often it crashes.......) .. no idea what would make the original work, and this one fail.  But thank you!

**Comment by ericblade** [comment]
it seems that something is blocking network traffic out of the container, and I don't even begin to fathom what would be doing that, how, or why.  But it is specific to this container, as none of my other containers (or kmb32123/youtube-dl-server) experience the same :| :|

**Comment by ericblade** [comment]
Mindbogglingly,

A reboot fixed it.

Thanks again  for checking!

**Comment by nbr23** [comment]
Yay for reboots! I'm glad you managed to get it running! No clue what this could have been yeah... Thx for the update!
