### ISSUE TITLE
Filename too long? 

### ISSUE THREAD

**Issue by mick-pihole** [nbr23/youtube-dl-server#11]
[youtube] mHhRQFknA0g: Downloading webpage
ERROR: unable to open for writing: [Errno 36] Filename too long: '/youtube-dlc/

anyway to trim the filename?

**Comment by nbr23** [comment]
A quick and easy workaround would be to edit `YDL_OUTPUT_TEMPLATE` in https://github.com/nbr23/youtube-dl-server/blob/master/ydl_server/config.py. Perhaps the title of the video you're trying to get makes the filename too long.
Would you be able to share a link that causes the issue?

Thanks!

**Comment by mick-pihole** [comment]
[shorturl.at/qLOQY](shorturl.at/qLOQY)

the problem is I'm using a web front end, I don't know how to make the web server use YDL_OUTPUT_TEMPLATE param.
I tried to edit config.py, that seems not fixing the issue. I guess the web server does not use YDL_OUTPUT_TEMPLATE

I am using https://github.com/dotpanic/youtube-dlc-server , and he forked your code.

**Comment by mick-pihole** [comment]
solved.
120 seenms too long..  👍 
change config.py to:
YDL_OUTPUT_TEMPLATE': '/youtube-dlc/%(title).50s [%(id)s].%(ext)s',
'YDL_OUTPUT_TEMPLATE_PLAYLIST': '/youtube-dlc/%(playlist_title)s/%(title).50s [%(id)s].%(ext)s',

**Comment by blackjack4494** [comment]
@mick-pihole 
I added a feature to trim long file names.  
You might want to give it a try.
