### ISSUE TITLE
privacy issue

### ISSUE THREAD

**Issue by helmut72** [nbr23/youtube-dl-server#110]
To have some privacy, I setup authentication before accessing youtube-dl-server URL, but exclude the path `/api/downloads` to use my bookmarklets easily.

But accessing `https://fqdn.of.my.instance>/api/downloads` with a webbrowser shows all logs of my latest downloads, if I'm not `purge logs` regularly in the webui.

Is it possible to change the path of the bookmarklet, that only the bookmarklet path need to be excluded and doesn't show logs of my downloads? Thanks.

**Comment by nbr23** [comment]
Hi @helmut72,

I don't know what you use for the auth setup but most reverse proxies will allow you to set up authentication only for some methods. In this case you could exclude POSTs requests from the auth requirement (see http://nginx.org/en/docs/http/ngx_http_core_module.html#limit_except for nginx for example).

There's no immediate plan to change the routes as it would likely break other people's setups.

Also please keep in mind that youtube-dl-server is not meant to be exposed on the internet, so I wouldn't recommend exposing any of the endpoints without authentication.

Cheers!

**Comment by helmut72** [comment]
> that youtube-dl-server is not meant to be exposed on the internet

Especially on the go I don't have time sending urls via chat or mail.

> I wouldn't recommend exposing any of the endpoints without authentication.

That's the reason I have enabled authentication. But not for the bookmarklet. If something is inconvenient to use, I use it less or not at all.

> In this case you could exclude POSTs requests from the auth requirement

Thanks, great idea! Will close this issue.

**Comment by helmut72** [comment]
Just for records, also OPTIONS request need to be skipped. For oauth2-proxy it's this setting:

```
OAUTH2_PROXY_SKIP_AUTH_ROUTES=OPTIONS=/api/downloads,POST=/api/downloads
```
