### ISSUE TITLE
Select Audio-language

### ISSUE THREAD

**Issue by Naimkr27** [nbr23/youtube-dl-server#111]
Hello Max,

thank you for coding youtube-dl-web interface.

I will download the film from this Website https://watch.thechosen.tv/video/184683594324 it is a multilanguage-film.

When i Downlaod the Film with the youtube-dl i don´t have a audio.

When i go to inspect in the web interface i habe a lot of links. 

How i can select german-language und the Videoformat and can safe as a file in mp4-Format?

Thank you

Naim

**Comment by nbr23** [comment]
Hi @Naimkr27, thanks, that's a great issue, I'm working on a fix!

**Comment by nbr23** [comment]
alright @Naimkr27 you should be able to do this now by hitting "Inspect" instead of "Download" on the homepage once you've pasted your video's url. A pop up should show up giving you a choice of all the formats available. Your favorite language should be in the list.

It's not perfect but should be a good workaround. As far as I know youtube-dl/yt-dlp don't provide a way to filter for a specific language

**Comment by nbr23** [comment]
Thanks @Naimkr27, I see exactly what you mean, and for a second I thought it would work. Unfortunately, after digging, the `--audio-format` flag that youtube-dl has only allows you to specify something from that list:
```
--audio-format FORMAT                Specify audio format: "best", "aac",
                                     "flac", "mp3", "m4a", "opus", "vorbis",
                                     or "wav"; "best" by default; No effect
                                     without -x
```
It does not allow us to specify a format from the metadata (like `AUDIO-German` in your case).

Your use case and all make a lot of sense to me though, so might be worth submitting a feature request to yt-dlp or youtube-dl...

I think that puts us at a dead end for your use case though. I'll keep digging in case I can hack something around, but not very hopefuly.... Sorry and thanks for the help figuring this out!!

**Comment by nbr23** [comment]
alright my bad, you're right it's totally doable. The command is `yt-dlp URL --audio-multistreams --format bestvideo+AUDIO-German`

Let me get to work to have this handled in youtube-dl-server and we'll be good to go 🍾

**Comment by nbr23** [comment]
should be good now, same steps as before! let me know 🤞

**Comment by Naimkr27** [comment]
@nbr23 Thanks, is working :-)
