### ISSUE TITLE
wrong link format

### ISSUE THREAD

**Issue by blackerking** [nbr23/youtube-dl-server#112]
Hey there

It seems subfolder management is mishandled with the links.
logs.vue:
![grafik](https://github.com/nbr23/youtube-dl-server/assets/2019363/2bd671e8-f02e-4560-94fc-8930ffdfa7bd)

I'm getting redirected to the wrong path.
![grafik](https://github.com/nbr23/youtube-dl-server/assets/2019363/fab375de-6726-4329-9c4f-09f88b466944)

Instead of:
![grafik](https://github.com/nbr23/youtube-dl-server/assets/2019363/d7090003-ae4c-4bf7-bd44-79ac27727242)

**Comment by nbr23** [comment]
Thx for the report @blackerking ! I *think* I fixed it, can you pull the latest and let me know?

Cheers!
