### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by twist3dimages** [nbr23/youtube-dl-server#113]
I'm getting error 403 on certain sites (a specific nsfw one) now, how easy would it be to add this? [https://github.com/lwthiker/curl-impersonate](url) someone mentioned a solution here [https://github.com/yt-dlp/yt-dlp/issues/6546#issuecomment-2037873707](url) 

edit: not sure why the link isn't working https://github.com/yt-dlp/yt-dlp/issues/6546#issuecomment-2037873707

**Comment by nbr23** [comment]
Hey @twist3dimages, this would be something for yt-dlp to fix, not something I can do much about at youtube-dl-server's level unfortunately.
