### ISSUE TITLE
[bug] CERTIFICATE_VERIFY_FAILED error after yesterday upgrade

### ISSUE THREAD

**Issue by leo15dev** [nbr23/youtube-dl-server#118]
Error in metadata fetching process:
ERROR: [generic] Unable to download webpage: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Error during download task:
Exception:
        ERROR: [generic] Unable to download webpage: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

even if you added   no-check-certificate: True in config.yml, still have the same issue

**Comment by nbr23** [comment]
Hi @leo15dev, this doesn't seem likely to have been caused by the latest upgrade. Does this happen for all videos? can you check if you can download them using yt-dlp directly?
I tried a couple of videos and am not having any issues.

**Comment by leo15dev** [comment]
@nbr23 It seems to be a problem with the tokyomotion.net website. Even if I use yt-dlp 2024.04.09, I can't download it. But the strange thing is that I could download it normally before the problem occurred, but now I can't download it. Thanks for your help, I will close this issue.
