### ISSUE TITLE
Worked at first now outputs error

### ISSUE THREAD

**Issue by Matthww** [nbr23/youtube-dl-server#12]
Hi after 1 video I downloaded I keep getting this error:

```
Added url https://www.youtube.com/watch?v=zgIilRcFEN8 to the download queue
10.0.0.104 - - [30/Sep/2020 15:48:42] "POST /api/downloads HTTP/1.0" 200 107
Exception during download task:
super(type, obj): obj must be an instance or subtype of type
```

**Comment by nbr23** [comment]
Hi @Matthww,
I checked but did not get any issues. Can you give more info on your setup, versions, and youtube-dl version used?

Thanks!

**Comment by UAEpro** [comment]
I got the same error 
`super(type, obj): obj must be an instance or subtype of type`

**Comment by nbr23** [comment]
Hi @UAEpro, can you share more info on your setup, how you run youtube-dl-server (directly ? docker ? if so, share your docker-compose ?) so I can help you out?

Cheers!

**Comment by Matthww** [comment]
Sorry for the late reply. I have no idea what youtube_dl version etc I was using back then. I just got the time to reinstall everything and I will report back with the info if the problem occurs again!

**Comment by nbr23** [comment]
Sounds good, thanks @Matthww !
