### ISSUE TITLE
When Downloading Playlists Issues with Dynamic Folders 

### ISSUE THREAD

**Issue by Dgenner** [nbr23/youtube-dl-server#122]
Hey there, appreciate all the work you've put into this great tool.  This is fairly minor but I notice when I dynamically create folders (ex. below).  That it properly creates subfolders based on the playlist name and correctly names the files, however, the entry in the "finished" files section shows a single item with the play list name instead of a subfolder and clicking on the item shows a "not found" message.

output: '/youtube-dl/Music/%(playlist_title)s/%(playlist_title)s - %(playlist_index)03d - %(title)+.100U [%(id)s]'

Running yt-dlp, on docker.

**Comment by nbr23** [comment]
Hi @Dgenner,

Thanks for the report! I'm not able to reproduce this. Can you give me more info / some screenshots / example of what the `/youtube-dl/Music` folder tree looks like on your filesystem?

**Comment by Dgenner** [comment]
I'm using the formatting to dynamically create a folder based on the playlist title.  It properly creates the folder and saves the files.  But when checking the finished file section it just shows the playlist name.  Clicking it just shows a not found message - it doesn't impact the downloading or folder creation or anything.  It just doesn't seem to recognize the the dynamically created folder as a folder.

As an example: 
playlist: https://www.youtube.com/playlist?app=desktop&list=PLCNFJ7TeOWzbVwtIPmocyLj16TofBhTQN
config: '/youtube-dl/Music/%(playlist_title)s/%(playlist_title)s - %(playlist_index)03d - %(title)+.100U [%(id)s]'

Gives me this:
![Finished](https://github.com/user-attachments/assets/0091a18f-cac4-4fee-acb3-a54b830450ba) 
Clicking through gives a "not found" message.

**Comment by nbr23** [comment]
Thanks @Dgenner, this was super helpful!
I believe it should now be fixed! Let me know if not.

Cheers!

**Comment by Dgenner** [comment]
Everything is working great.  Thanks so much.
