### ISSUE TITLE
some images don't seem to work

### ISSUE THREAD

**Issue by simonmcnair** [nbr23/youtube-dl-server#124]
I tried using nbr23/youtube-dl-server:latest and was getting 'ERROR: Unable to extract uploader id;'

I thought I'd try   nbr23/youtube-dl-server:youtube-dl 

and got 
`Error during download task:
Exception:
	ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/youtube_dl/extractor/youtube.py", line 1367, in _decrypt_signature
    return func(s)
  File "/usr/local/lib/python3.13/site-packages/youtube_dl/extractor/youtube.py", line 1266, in <lambda>
    return lambda s: ''.join(s[i] for i in cache_spec)
                     ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/youtube_dl/extractor/youtube.py", line 1266, in <genexpr>
    return lambda s: ''.join(s[i] for i in cache_spec)
                             ~^^^
TypeError: string indices must be integers, not 'str'
 (caused by TypeError("string indices must be integers, not 'str'")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

finally I tried nbr23/youtube-dl-server:yt-dlp and success.

I would advise removing the other two images as they don't work from what I can see.
Cheers

**Comment by nbr23** [comment]
Thanks yeah youtube-dl stopped doing package release a few years back, so definitely not the best image to use.
I've swapped `latest` to point to the `yt-dlp` image to avoid these issues.

Thanks again!
