### ISSUE TITLE
Kodi integration and NFO-file creation?

### ISSUE THREAD

**Issue by nickv2002** [nbr23/youtube-dl-server#14]
I made a fork of this project and added [NFO-file creation](https://kodi.wiki/view/NFO_files) ([sample code](https://github.com/ToWatchList/twl-dl-server/blob/main/ydl_server/ydlhandler.py#L172-L207)) and basic [Kodi](https://kodi.tv) library integration ([sample code](https://github.com/ToWatchList/twl-dl-server/blob/main/youtube-dl-server.py#L123-L138)).

I can cut out these updates from my fork and PR them back into this repo if you have any interest in folding them in here – let me know.

Either way, thanks for the neat project!

**Comment by nbr23** [comment]
Hey @nickv2002,

Really cool work, thanks for linking to it!
I don't think merging it back is necessarily the best idea, while there's definitely value in your patches, they are a tad specific, and I would like to keep the main branch as generic and lightweight as possible.
I would be happy to add a link to your fork/patch in the README for easy access to users interested in kodi integrations if you plan to keep it up though!

Cheers,
Max

**Comment by nickv2002** [comment]
Sounds good.
Let me polish some more things up and then I'll post here again and you can link.
Thanks.

**Comment by nickv2002** [comment]
I think my repo is performing pretty well now after testing for the last month. (Had a move over that time too so it took a while!). In any case if folks are looking for a version that can write metadata into Kodi-compatable NFOs and/or something that integrates with ToWatchList.com (a watch-later service I run) they can check out [twl-dl-server](https://github.com/ToWatchList/twl-dl-server) and you're welcome to link to it in a note somewhere @nbr23

Thanks for all your work on this project. It's working great!
