### ISSUE TITLE
add an option for the quality of videos higher than 1080

### ISSUE THREAD

**Issue by Naimkr27** [nbr23/youtube-dl-server#17]
Can you add this option? I will have the Videos in best quality. I have a 4K TV

**Comment by nbr23** [comment]
Hi @Naimkr27,
If you select the "best" video option in the dropdown menu, you should be getting the highest quality format available.
Note that some services might not offer anything higher than 1080p.

I just did a quick test with this random video that offers 4k (2160p): https://www.youtube.com/watch?v=6pxRHBw-k8M

If we check the metadata, we see in the formats list the 2160p, which weighs 328.53 MB:
![image](https://user-images.githubusercontent.com/1313493/99130633-c7e1f400-2608-11eb-94b4-74913880415d.png)

Downloading selecting Best:
![image](https://user-images.githubusercontent.com/1313493/99130574-a2ed8100-2608-11eb-82a5-4e86f232a6fb.png)

We can see the size seems to match with the 2160p:
![image](https://user-images.githubusercontent.com/1313493/99130540-8b15fd00-2608-11eb-9539-471a041f7908.png)
And we can validate on the file directly:
![image](https://user-images.githubusercontent.com/1313493/99130860-74bc7100-2609-11eb-95bd-b22eb681ee58.png)
