### ISSUE TITLE
Raspbian

### ISSUE THREAD

**Issue by Naimkr27** [nbr23/youtube-dl-server#18]
Can you make a Container for the Raspberry Pi 4 with Raspbian.

Thanks.

**Comment by nbr23** [comment]
Hi @Naimkr27,
Unfortunately, I don't think I can autobuild for arm on Dockerhub, which makes it a bit more cumbersome to have an arm image easily available.
Until I set something up, you can build it locally from the git repo.
I also have an ansible role that can help you out, it builds and deploys the container on the target: https://github.com/nbr23/ansible-role-youtubedl-server

Cheers,
Max

**Comment by Naimkr27** [comment]
Hi @nbr23,

thanks for your answer.
ich habe a problem, i don´t can start the Server.

This is the answer of the Program.
Using youtube-dl module
Traceback (most recent call last):
  File "./youtube-dl-server.py", line 119, in <module>
    JobsDB.check_db_latest()
  File "/home/pi/yt/youtube-dl-server/ydl_server/logdb.py", line 58, in check_db_latest
    conn = sqlite3.connect("file://%s" % app_defaults['YDL_DB_PATH'], uri=True)
sqlite3.OperationalError: unable to open database file
 Can i help me.

Thanks.

**Comment by nbr23** [comment]
@Naimkr27,
Make sure the value of YDL_DB_PATH in the config file points to a valid directory and that the user running youtube-dl-server.py has write access to that folder.
This is most likely a rights issues, or the directory not existing.

Cheers,
Max

**Comment by Naimkr27** [comment]
Sorry Max, i don‘t can download Videos.
The Button don‘t work. And the Site are Not Complett load.
![AAE55DA4-C1C7-48F9-BDAF-8F46578E4DDD](https://user-images.githubusercontent.com/64653285/99307424-c73e9d00-2856-11eb-92b1-efe1aac7a57d.png)

**Comment by nbr23** [comment]
Easy fix, this is because you are missing the web libraries (bootstrap, jquery etc).
I have added a note in the README and a script to help out.
You can just run https://github.com/nbr23/youtube-dl-server/blob/master/bootstrap.sh once to download what is required and you should be good to go.

**Comment by Naimkr27** [comment]
Thanks, is run.
