### ISSUE TITLE
youtubedl is downloading in config folder

### ISSUE THREAD

**Issue by amitsax** [nbr23/youtube-dl-server#24]
Docker image does not seem to care for the YDL_ environment variable:
- YDL_OUTPUT_TEMPLATE=${YOUTUBEDL_OUTPUT_TEMPLATE}

When I tried to redirect config.yml to config folder using -
YDL_CONFIG_PATH=/youtube-dl/config.yml

I get these errors:

Traceback (most recent call last):
File "/usr/src/app/./youtube-dl-server.py", line 10, in
from ydl_server.logdb import JobsDB, Job, Actions, JobType
File "/usr/src/app/ydl_server/logdb.py", line 6, in
from ydl_server.config import app_config
File "/usr/src/app/ydl_server/config.py", line 14, in
app_config = load_config(config_path)
File "/usr/src/app/ydl_server/config.py", line 10, in load_config
config = yaml.load(configfile, Loader=yaml.SafeLoader)
File "/usr/local/lib/python3.9/site-packages/yaml/init.py", line 114, in load
return loader.get_single_data()
File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
node = self.get_single_node()
File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 39, in get_single_node
if not self.check_event(StreamEndEvent):
File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
self.current_event = self.state()
File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 171, in parse_document_start
raise ParserError(None, None,
yaml.parser.ParserError: expected '', but found ''
in "/youtube-dl/config.yml", line 8, column 1

**Comment by nbr23** [comment]
Hi @amitsax ,
Thank you for this issue, I will look into that!
Can you share the content of you `/youtube-dl/config.yml` as it seems there might be a syntax error in there?

The `YDL_OUTPUT_TEMPLATE` variable being ignored is something I am working on now and should resolve soon.

Cheers!

**Comment by angrycuban13** [comment]
Is `config.yml` a required file now?

**Comment by nbr23** [comment]
Hi @angrycuban13,
Thanks for the note, I actually was looking at DockSTARTer today and wanting to fix the config.yml issues, so I will check that right now.
Thanks for the explanations, much clearer to me now!

Cheers!

**Comment by nbr23** [comment]
@angrycuban13
Ok so I do copy a default config.yml in the image at build (not first run) https://github.com/nbr23/youtube-dl-server/blob/4e431005ae59277c9355154285a6f4faa228776a/Dockerfile#L16
If you removed `- ${DOCKERCONFDIR}/youtube-dl/config.yml:/usr/src/app/config.yml:ro` from your compose, you will get the default config.yml.

What I think you want us to accomplish here is for the image to create the config.yml file on the host system if it does not exist (through a mounted dir?).

So we could have something like this in your docker-compose:
`- ${DOCKERCONFDIR}/youtube-dl/config_dir:/usr/src/app/config_dir/`

And on my end I would check at startup if `/usr/src/app/config_dir/config.yml` exists in the container, and if not, write the default config file there ?
Let me know if I am totally off or if that's the idea, and we'll find a somewhat elegant way to do this :D 
Thanks!

**Comment by nemchik** [comment]
Correct @nbr23 that's exactly it.

**Comment by nbr23** [comment]
Alright @nemchik , @angrycuban13 I pushed some changed to [dev-config](https://github.com/nbr23/youtube-dl-server/commit/647273d4a78759a6393a996ca5244eec3f571d5c).
If you want to give it a shot, you can use the dev-config tag on the docker image `docker pull nbr23/youtube-dl-server:dev-config`. I still need to do a few more tests before merging into master but now a few scenarios are possible:

1. You run the container without any mounting or YDL_CONFIG_PATH set: the container will create a volume in /app_config, and copy the default config there and load it.
2. You run the container with a mount `${DOCKERCONFDIR}/youtube-dl/config_dir:/app_config` and no `YDL_CONFIG_PATH`: if `${DOCKERCONFDIR}/youtube-dl/config_dir/config.yml` exists, it will be loaded, if not it will be created with the default values, and then loaded
3. You run the container with a mount `${DOCKERCONFDIR}/youtube-dl/config_dir:/my_custom_dir_in_container` and `YDL_CONFIG_PATH=/my_custom_dir_in_container`: if `${DOCKERCONFDIR}/youtube-dl/config_dir/config.yml` exists, it will be loaded, if not it will be created with the default values, and then loaded
4. You run the container with a mount `${DOCKERCONFDIR}/youtube-dl/config_dir:/my_custom_dir_in_container` and `YDL_CONFIG_PATH=/my_custom_dir_in_container/my_custom_filename.yml`: if `${DOCKERCONFDIR}/youtube-dl/config_dir/my_custom_filename.yml` exists, it will be loaded, if not it will be created with the default values, and then loaded

I think that sums up most use cases, and this way it should not break any (most?) existing configuration.
Any feedback welcome, I will keep testing and update the README and then push to master.

Thanks!

**Comment by angrycuban13** [comment]
I think that definitely covers most bases. I will test all options and report back!

**Comment by angrycuban13** [comment]
Okay. I can verify that the first scenario works.

![first scenario](https://sharex.angrycuban.xyz/XExe1/xOcEraLo20.png/raw)

Second scenario seems to work as well:

![second scenario](https://sharex.angrycuban.xyz/XExe1/gARogULO88.png/raw)

Third scenario is working as well:
```yml
  environment:
    - YDL_CONFIG_PATH=/config
  volumes:
    - ${DOCKERCONFDIR}/youtube-dl/config:/config
 ```
![third scenario](https://sharex.angrycuban.xyz/XExe1/wOLinocE31.png/raw)

Fourth scenario also working:
```yml
  environment:
      - YDL_CONFIG_PATH=/config/youtube-dl_config.yml
  volumes:
    - ${DOCKERCONFDIR}/youtube-dl/config:/config
 ```
![fourth scenario](https://sharex.angrycuban.xyz/XExe1/RilIQERO14.png)/raw)

**Comment by nbr23** [comment]
Oh wow you are awesome, thanks a lot @angrycuban13

I did forget about people not using docker, so I pushed https://github.com/nbr23/youtube-dl-server/commit/9aebd64180e769d22765286eba25498bfe48d764 which sets `YDL_CONFIG_PATH` to /app_config in the Dockerfile, and otherwise in the python code, I will default to the current working directory for people who would be running it directly.

Adding a few notes to the README and then I will merge. Thanks !

**Comment by nbr23** [comment]
Merged in master. Thanks again for the valuable help on this @angrycuban13  @amitsax, and thanks for your adding this project to DockSTARTer!

I will leave this issue open as I still need to work on @nemchik's original ask about using environment variables to pass configuration items. I am still considering whether it is worth it / not too messy.

Cheers!
