### ISSUE TITLE
youtube-dl don´t start

### ISSUE THREAD

**Issue by Naimkr27** [nbr23/youtube-dl-server#26]
hi,

i have a Problem zu start youtube-dl

The Answer of this is:
Using youtube-dl module
Traceback (most recent call last):
  File "./youtube-dl-server.py", line 10, in <module>
    JobsDB.check_db_latest()
  File "/root/youtube-dl/ydl_server/logdb.py", line 58, in check_db_latest
    conn = sqlite3.connect("file://%s" % app_config['ydl_server'].get('metadata_db_path'), uri=True)
sqlite3.OperationalError: unable to open database file

Can i help me?

thanks

**Comment by nbr23** [comment]
Hi @Naimkr27 ,

Thanks for the issue, let's try to get you fixed up!
First of call, it seems you are running this locally, without docker, is that correct?
If that is the case, can you confirm the value of the `metadata_db_path` variable in `config.yml` in your setup?
If you have left it to the original value, then it will try to write the internal metadata in `/youtube-dl/.ydl-metadata.db`, which may not exist as a folder and file on your computer. It would result in the error you are seeing.
My recommendation: review the settings in `config.yml` and adjust the different paths (`metadata_db_path`, `output_playlist`, `output`, `cache-dir`) to make them point to directories that exist on your system.

Let me know if something is unclear or if you need more help.

Cheers!

**Comment by Naimkr27** [comment]
yes, is work.

thanks

**Comment by nbr23** [comment]
Great, thanks for the confirmation :)
