### ISSUE TITLE
How to terminate an ongoing task

### ISSUE THREAD

**Issue by PDSCi996** [nbr23/youtube-dl-server#29]
Handy, I added a youtube playlist with many files, and suddenly I don’t want to download it. Restarting the container will still continue. How can I terminate the download of this playlist, or terminate a task that is waiting to be downloaded.
Greatful.

**Comment by nbr23** [comment]
keeping this open, I am working on something :)

**Comment by PDSCi996** [comment]
> keeping this open, I am working on something :)

Don't worry,you are busy first,and it has caused you a lot of trouble recently :)

**Comment by nbr23** [comment]
Closing with https://github.com/nbr23/youtube-dl-server/commit/e71f625762509ccb158604f9cb31b7ea4e0e2f60
