### ISSUE TITLE
Youtube-dl gives error extracting video data on playlists and does not process any videos in list

### ISSUE THREAD

**Issue by RibbonMoon** [nbr23/youtube-dl-server#3]
Is it possible to implement a feature that allows Youtube-dl to ignore errors in playlists and continues to the next item, the CLI has the --ignore-errors that can be used, but I cannot see any way to pass this to the docker version.

**Comment by nbr23** [comment]
Thanks @RibbonMoon for this issue.
Would you have a playlist with errors you can share so I can do some tests around this?
Cheers,
Max

**Comment by RibbonMoon** [comment]
Hi

The URL i was trying was https://www.youtube.com/playlist?list=PLKf0gyS5rgHfV0C_Hp7ywR5sxwvUK1lX0 for my elderly parents who love Andre Rieu, However the first concerts have now been removed by youtube, What I was trying to do was to download the ones that were left in the list.


All the best.

Ribbon

**Comment by nbr23** [comment]
Thanks @RibbonMoon !
https://github.com/nbr23/youtube-dl-server/commit/9267f59221bc048301afe120d3303936fedf6cf9 adds the possibility to pass any argument to youtube-dl's engine. As a default in the config, I have made it ignore errors on playlist downloads (by passing 'ignoreerrors').
All you should need is to pull the latest.

Cheers!
Max

**Comment by RibbonMoon** [comment]
This works perfectly now and downloads the lists fine. thanks.

**Comment by nbr23** [comment]
Awesome, thanks for the feedback :)
