### ISSUE TITLE
Extent of the included API

### ISSUE THREAD

**Issue by the-researcher** [nbr23/youtube-dl-server#35]
Hi nbr23!

On the main page, you provide guidance on how to send a URL to the docker image, along with the video format.

Knowing this, is it possible to parse specific commands that would override the defaults located in the `config.yml` file? By default, I would like to keep my current settings as default (1080, with .mp4), but there are times where I would prefer the 720 at .mp4 format for other series.

If I parse just the URL, the download fails, as my default settings ask for 1080, and the 1080 video format isn't available for the URL I'm sending to the server, only 720. Likewise, I also don't want to mix formats (i.e. avoiding mixed resolution season packs aka 720 with 1080 as a single season; either 720 or 1080 for a whole season of shows).

Is there a way where - in addition to sending the URL - I can also send specific format conditions that override default settings?

I know that you provide the following options:
- `url`
- `format` (which I'm guessing is following the drop-down menu

Are there other options available within the API? And if other options exist, would these options override the default options listed in the `config.yml` file?

Thanks,

the_researcher

**Comment by nbr23** [comment]
Hi @the-researcher,

> format (which I'm guessing is following the drop-down menu
You are right, format is the same as the dropdown menu. This should however help you in your use case as you could perhaps pick a lower quality format?

There are no other options supported through the API, and I probably will not be adding more.
youtube-dl's options are quite extensive and this would quickly become difficult to maintain and could create security issues on some options.

nbr23
