### ISSUE TITLE
Error on startup: database is locked

### ISSUE THREAD

**Issue by redec** [nbr23/youtube-dl-server#36]
I'm trying to run this on a raspberry pi - I built my own docker image (as there isn't one available for arm) but when I try to start the image I get this:

```
Using configuration file /app_config/config.yml
/app_config/config.yml does not exist, creating it from default values
Outdated jbos table, cleaning up and recreating
Traceback (most recent call last):
  File "./youtube-dl-server.py", line 20, in <module>
    JobsDB.init_db()
  File "/usr/src/app/ydl_server/logdb.py", line 71, in init_db
    cursor.execute("CREATE TABLE if not exists jobs \
sqlite3.OperationalError: database is locked
```

**Comment by redec** [comment]
My bad....permissions issue

**Comment by ksurl** [comment]
I am still getting this error on amd64 build. what permissions did you need to change? starting from a brand new container and default config. mapped file and the youtube-dl folder

**Comment by ksurl** [comment]
I ended up editing the config.yml to change the folder of the metadata db to be in the same folder as the config file /app_config. shouldn't that be the default? and maybe rename /youtube_dl to /downloads or not require it as a volume in the Dockerfile (otherwise it creates a randomly named volume)
