### ISSUE TITLE
Arm/Raspberry Pi compatibility

### ISSUE THREAD

**Issue by Borkuz** [nbr23/youtube-dl-server#4]
I would love to see arm/raspberry pi compatibility. If you need help testing I'm willing to help you!

**Comment by nbr23** [comment]
Hi @Borkuz,
I had a Pi 3 B+ hanging around and gave it a shot, seems to be working fine out of the box in there.
If you want to try it out and let me know if you get any issues that would be great!

Cheers,
Max

**Comment by Borkuz** [comment]
I just tried to run it on my rpi4 running the latest version of raspbian and get the following error in the log `standard_init_linux.go:211: exec user process caused "exec format error"`

The command I ran was `docker run -d --name youtube-dl -v /mnt/share/youtube-dl:/youtube-dl nbr23/youtube-dl-server`

Is pulls all the required files but can't seem to start for some reason

**Comment by nbr23** [comment]
Ah yes I see, indeed if you try to pull from docker hub it won't give you an arm image but the x86_64 image that it builds automatically from github.
The easiest would be to build the image on your pi yourself (that's what I did here):
`docker build https://github.com/nbr23/youtube-dl-server.git -t youtube-dl-server`
And then run your container.
Cheers,
Max

**Comment by Borkuz** [comment]
I'm getting closer, after running above command but still get an error.
`Outdated jbos table, cleaning up and recreating,
Traceback (most recent call last):,
  File "./youtube-dl-server.py", line 114, in <module>,
    JobsDB.init_db(),
  File "/usr/src/app/ydl_server/logdb.py", line 72, in init_db,
    cursor.execute("CREATE TABLE if not exists jobs \,
sqlite3.OperationalError: database is locked,`


i think this is an error with the permissions  on (in my case) `/mnt/share/youtube-dl`

**Comment by nbr23** [comment]
Yes that sounds like a permission problem on your station. Make sure the share is writeable by the user the container runs as and you should be good to go :)
