### ISSUE TITLE
Error when downloading with best audio

### ISSUE THREAD

**Issue by DavidPackard** [nbr23/youtube-dl-server#42]
Tried to download a video with the 'best audio' setting, and was met with this response.
Probably a bug, thought I'd let you know
![image](https://user-images.githubusercontent.com/33271469/114671582-681c8000-9d43-11eb-9ba2-f690493d751d.png)

**Comment by nbr23** [comment]
Thanks @DavidPackard , https://github.com/nbr23/youtube-dl-server/commit/62c0175a5d14578e106a2e1fd876a8afff6df0b9 should fix this issue.
