### ISSUE TITLE
Nitter

### ISSUE THREAD

**Issue by Thespikedballofdoom** [nbr23/youtube-dl-server#47]
I pulled my hair out all day looking for a way to download nitter videos quickly and easily. The original youtube-dl app supports the domains, why do none of the apps?

**Comment by nbr23** [comment]
hi @Thespikedballofdoom,
I don't know nitter, if possible, can you share a problematic link so I can debug?

Cheers!

**Comment by Thespikedballofdoom** [comment]
https://nitter.domain.glass/EmperorLemon/status/1348827416844754944#m

**Comment by nbr23** [comment]
I just tried with the original `youtube-dl`, and I am not able to download the video. Can you confirm you can on your end? If so, which version of youtube-dl are you using?

```
youtube-dl 'https://nitter.domain.glass/EmperorLemon/status/1348827416844754944#m'
[generic] 1348827416844754944#m: Requesting header
WARNING: Could not send HEAD request to https://nitter.domain.glass/EmperorLemon/status/1348827416844754944#m: HTTP Error 404: Not Found
[generic] 1348827416844754944#m: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 1348827416844754944#m: Extracting information
ERROR: Unsupported URL: https://nitter.domain.glass/EmperorLemon/status/1348827416844754944#m
```

**Comment by Thespikedballofdoom** [comment]
Nvm, looks like i was using youtube-dlc. (that being said if its easy to implement it has like has more sites as options)


Thanks

**Comment by nbr23** [comment]
I see. You can use youtube-dlc, but you will need to build the docker image image yourself:
`docker build -t youtube-dlc-server --build-arg YOUTUBE_DL=youtube_dlc .`

I have stopped pushing youtube-dlc images as the youtube-dlc project seems inactive.
