### ISSUE TITLE
AttributeError: module 'ydl_server.views' has no attribute 'api_list_finished'

### ISSUE THREAD

**Issue by SugiuraAyano** [nbr23/youtube-dl-server#49]
I'm using this server on my synology nas docker and new update show this error message on startup

```
Using configuration file /app_config/config.yml

Traceback (most recent call last):

  File "/usr/src/app/./youtube-dl-server.py", line 16, in <module>

    from ydl_server.routes import routes

  File "/usr/src/app/ydl_server/routes.py", line 18, in <module>

    Route("/api/finished", views.api_list_finished, name="api_list_finished"),

AttributeError: module 'ydl_server.views' has no attribute 'api_list_finished'
```
and server shutdowns

**Comment by SugiuraAyano** [comment]
I've looking the lasted commit and seems you edit api_list_finished to front_finished in views.py

**Comment by nbr23** [comment]
woops, thanks for the report @SugiuraAyano, fixed here https://github.com/nbr23/youtube-dl-server/commit/a234d3e0a18b11c61177ae3f98e90db9e75744dd
Let me know if you still have issues!

**Comment by xnaas** [comment]
I pulled and am using https://hub.docker.com/layers/nbr23/youtube-dl-server/youtube-dl/images/sha256-4b01699d8ea00d32523bb99d14d1a332a0d88417dd030099dae0732249a14698 and am still getting:

```py
Using configuration file /app_config/config.yml
Traceback (most recent call last):
  File "/usr/src/app/./youtube-dl-server.py", line 16, in <module>
    from ydl_server.routes import routes
  File "/usr/src/app/ydl_server/routes.py", line 18, in <module>
    Route("/api/finished", views.api_list_finished, name="api_list_finished"),
AttributeError: module 'ydl_server.views' has no attribute 'api_list_finished'
```

**Comment by SugiuraAyano** [comment]
Thanks for quick reply. The new images in docker hub fix this issue
will close this now

**Comment by nbr23** [comment]
@xnaas just reran the github action to build and it seems good now.
Not sure whate happened the first time.

**Comment by xnaas** [comment]
Working great again. Thanks. :)
