### ISSUE TITLE
Opus Quality is a mess

### ISSUE THREAD

**Issue by blackerking** [nbr23/youtube-dl-server#50]
Some time ago the standard opus files where in a good condition.
Now all downloaded files with this format has a very low quality(but a good file size 🤷‍♂️ ).

**Comment by nbr23** [comment]
Hi @blackerking,
I am not sure what issue you are reporting here or what you expect to be done at youtube-dl-server's level.

Thanks for any clarification :)

**Comment by blackerking** [comment]
Did you changed some standard parameters?

**Comment by nbr23** [comment]
No changes on my end no. Might be in youtube-dl itself? or youtube?

**Comment by blackerking** [comment]
It seems this problem is gone. I don't know where it came and how it is gone.

**Comment by nbr23** [comment]
Ok, thanks for the update!
