### ISSUE TITLE
AtomicParsley - UnicodeDecodeError in some video downloads

### ISSUE THREAD

**Issue by PDSCi996** [nbr23/youtube-dl-server#52]
Today I upgraded the latest version of "youtube-dl_atomicparsley", and the following error message appears when downloading the video
"Error during download task:
UnicodeDecodeError:
'utf-8' codec can't decode bytes in position 4094-4095: unexpected end of data"
I hope it will be helpful to improve and trouble you.

**Comment by nbr23** [comment]
Hi @PDSCi996 do you have a specific video that causes the issue?
I just tried a random video and had no issues.

Thanks!

**Comment by nbr23** [comment]
Hi @PDSCi996  do you have a specific video that causes the issue?
I just tried a random video and had no issues.

Thanks!
