### ISSUE TITLE
Alpine 3.14 on aarch64 - libsqlite segfault 

### ISSUE THREAD

**Issue by nbr23** [nbr23/youtube-dl-server#53]
Documenting in case anyone else is having issues:

I have been experiencing segfaults and application crash on alpine 3.14 on aarch64 when doing simple selects with sqlite3 through python.
 dd4d3c745f3b4cfdf33842a654a11f50d8dc3d25 fixes this temporarily (by using alpine 3.13) until the libsqlite version gets bumped, or this problem gets sorted out.

**Comment by nbr23** [comment]
@Skaronator oh yeah good call. I just tested 3.17 and that segfault with sqlite on aarch64 seems gone!
Switched us to alpine3.17, the docker image should get pushed shortly!

Thx!

**Comment by nbr23** [comment]
Image is out on dockerhub btw. Got delayed a bit on arm64, but we'are all set. Thanks again!

**Comment by Skaronator** [comment]
Thanks for the quick response! :)
