### ISSUE TITLE
[FEATURE] Set default format via config

### ISSUE THREAD

**Issue by NemesisRE** [nbr23/youtube-dl-server#54]
As I am mostly wanne download MP3 files it would be nice to be able to set the default selected format via config

```
ydl_server:   # youtube-dl-server specific settings
  format: MP3      # Format the is selected by default on the page
```

**Comment by Thespikedballofdoom** [comment]
is there a way to do something like this in the bookmarklet also

**Comment by NemesisRE** [comment]
I have a bookmarklet for that

`javascript:fetch("https://[myhost]/youtube-dl/api/downloads",{body:newURLSearchParams({url:window.location.href,format:"MP3"}),method:"POST"});`

but despite the fact that the bookmarklet is not working for me (not even the default one), I still wish the config would allow to set a default format

**Comment by nbr23** [comment]
Thanks for the suggestion / issue @NemesisRE 
This is now in place. In your case, you can use:

```yaml
ydl_server:   # youtube-dl-server specific settings
  default_format: audio/mp3  # Default format selection
```

**Comment by NemesisRE** [comment]
Nice, thank you 😀
