### ISSUE TITLE
yt-dlp Update issue

### ISSUE THREAD

**Issue by nickv2002** [nbr23/youtube-dl-server#56]
For whatever reason **yt-dlp** from pip requires `gcc` and `musl-dev` packages to install now.

So these are available here:
https://github.com/nbr23/youtube-dl-server/blob/47deb2f9ae363d968732146922c8f3652ffbe2df/Dockerfile#L8

But are not in the final docker file:
https://github.com/nbr23/youtube-dl-server/blob/47deb2f9ae363d968732146922c8f3652ffbe2df/Dockerfile#L20

Easy solution, add those packages to line 20.
Alternative possibility, use a different install/upgrade scheme to update eg `yt-dlp -U` after making those packages available for initial build.

**Comment by nbr23** [comment]
Thanks for the report @nickv2002, this should be fixed with https://github.com/nbr23/youtube-dl-server/commit/4855344e1ebe094e1c7e464891df49b3b1e951e4
