### ISSUE TITLE
run with User www-data

### ISSUE THREAD

**Issue by Naimkr27** [nbr23/youtube-dl-server#60]
Hello,

can i run the YouTube-DL with the User www-data?

What is the correctly Command?

Thanks Naimkr2709

**Comment by nbr23** [comment]
Hi @Naimkr27,

Sorry for the late reply! You should be able to accomplish this with the `--user ` parameter of the docker command-line.

docker-compose also allows this with the user directive.

**Comment by Naimkr27** [comment]
Hi, @nbr23,

thanks for the answer.

It is runing.

Best regards
