### ISSUE TITLE
How to switch to yt-dlp?

### ISSUE THREAD

**Issue by gambra** [nbr23/youtube-dl-server#61]
I saw the variable mentioned on the main page but I can't see to get it to apply, its still running youtube-dl. I'm likely doing it very wrong haha. Any advice?

```
PGID=1000
PUID=1000
TZ=Europe/Dublin
YDL_DEBUG=false
YDL_CONFIG_PATH=/youtube-dl/config.yml
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG=C.UTF-8
GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D
PYTHON_VERSION=3.10.0
PYTHON_PIP_VERSION=21.2.4
PYTHON_SETUPTOOLS_VERSION=57.5.0
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/3cb8888cc2869620f57d5d2da64da38f516078c7/public/get-pip.py
PYTHON_GET_PIP_SHA256=c518250e91a70d7b20cceb15272209a4ded2a0c263ae5776f129e0d9b5674309
YOUTUBE_DL=yt-dlp python3 -u ./youtube-dl-server.py
YDL_PYTHONPATH=/youtube-dl/.python
```

**Comment by nbr23** [comment]
Hi @gambra, can you let me know more about how you are using youtube-dl-server ? Are you using docker, or running it directly ?
Thanks!

**Comment by quorn23** [comment]
This looks like docker, as i'm facing the same issue

I see
`today at 16:07:32no such option: -u`

when using
`YOUTUBE_DL=yt-dlp python3 -u ./youtube-dl-server.py`
as environment variable in compose

I tried with just "yt-dlp" and that starts up with the note it can't find the module

**Comment by nbr23** [comment]
@quorn23 all you need to get yt-dlp is to use use the image `nbr23/youtube-dl-server:yt-dlp` instead of `nbr23/youtube-dl-server:latest`

Cheers!

**Comment by quorn23** [comment]
@nbr23 oh shame on me, i didn't even looked at the tags. That did the trick. Thanks!
Might be worth adding a note at the different forks section in the read me, for other lost sheeps :)

**Comment by nbr23** [comment]
will do, thanks!

**Comment by nbr23** [comment]
https://github.com/nbr23/youtube-dl-server/commit/3ca97f493063600b577fba3396e19736449c3932
