### ISSUE TITLE
Concurrent downloads

### ISSUE THREAD

**Issue by iaredavid01** [nbr23/youtube-dl-server#64]
I'm running in a Docker container and I'd like be able to download multiple, concurrent live streams. It'd be nice to set a number of concurrent downloads, or maybe allow live streams to be downloaded concurrently while the rest of the queue is sequential?

Right now, I'm getting around this by manually downloading the file by running a `docker exec yt-dlp ....` command, so I'm covered for now, but I'm sure this could feature seems useful.

**Comment by twist3dimages** [comment]
I would like to know this as well

**Comment by nbr23** [comment]
Thanks, still considering this, I'll try to follow-up soonish!

**Comment by twist3dimages** [comment]
Thank you!

**Comment by twist3dimages** [comment]
> Thanks, still considering this, I'll try to follow-up soonish!

Hey, not trying to be a dick or anything, but is there a reason why that functionality was removed from the manbearwiz fork?

**Comment by nbr23** [comment]
Hey, thx for following up here! Honestly I forked it 2yrs (?) ago, and don't remember removing this, so maybe it was added there post-fork? If the removal is on me, then my excuse is probably wanting to keep this as simple as possible. But I do think it makes sense to make this work, so I'll work this (back?) in!
Cheers, thanks again for pushing for improvements!

**Comment by twist3dimages** [comment]
Thank you for being responsive, sorry if my last response came off harsh. I really appreciate it

**Comment by john2069** [comment]
Hi @nbr23 , thanks again for this great fork.  Wondering if you're still keen to add this functionality?

**Comment by nbr23** [comment]
Working on it! :)

**Comment by nbr23** [comment]
Alright, done with https://github.com/nbr23/youtube-dl-server/commit/21a1379994b99dbde3f86b51e9a70744ca43a207
I'm defaulting it to `2` workers, you can increase it by playing with [download_workers_count](https://github.com/nbr23/youtube-dl-server/blob/master/config.yml#L11) in your config file.

Please let me know (by opening an issue) if you get any problems!
Sorry it took me so long to get convinced to work this in!

Thanks everyone <3

**Comment by twist3dimages** [comment]
Thank you!!!!

**Comment by john2069** [comment]
Thank you so much!
