### ISSUE TITLE
yt-dlp armv7 image fails to update

### ISSUE THREAD

**Issue by redec** [nbr23/youtube-dl-server#66]
I've just switched to using the yt-dlp image on a raspberry pi, and the automatic update fails reliably with compile errors. It seems brotli and pycryptodomex do not have armv7 wheels available, so it attempts to compile them and fails because gcc is not in the image. The full error message is far too much to paste here, but this is the gist of it

```
Building wheels for collected packages: brotli, pycryptodomex, websockets
Building wheel for brotli (setup.py): started
Building wheel for brotli (setup.py): finished with status 'error'
error: subprocess-exited-with-error

...snip...

gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -Ic/include -I/usr/local/include/python3.10 -c c/common/constants.c -o bin/temp.linux-armv7l-3.10/c/common/constants.o
error: command 'gcc' failed: No such file or directory

...snip (several more gcc errors like that)...

Successfully built websockets
Failed to build brotli pycryptodomex
Installing collected packages: certifi, brotli, websockets, pycryptodomex, mutagen, yt-dlp
Running setup.py install for brotli: started
Running setup.py install for brotli: finished with status 'error'
error: subprocess-exited-with-error
```

The youtube-dl armv7 image does not have this problem, so these seem to be dependencies unique to yt-dlp. Would it be possible to include `build-essential` in the armv7 yt-dlp image?

**Comment by nbr23** [comment]
Hi @redec, thanks for the report, I'm going to look into this.

In the meantime, I've added a quick bypass so you can keep using it.
In your config.yml, add `no_updates: true` under `ydl_server`:L

```
ydl_server:   # youtube-dl-server specific settings
  no_updates: true
```
And it will skip updates and let you start the app.

Thanks again, I'll work on a better fix soon.

**Comment by nbr23** [comment]
I removed the auto-update feature altogether as it was unstable and added issues more than anything.
Pulling the container will be the supported way to update youtube-dl/yt-dlp from now on.
Thanks!
