### ISSUE TITLE
How to use YDL_RAW_OPTIONS 

### ISSUE THREAD

**Issue by sanmadjack** [nbr23/youtube-dl-server#7]
I don't understand how I can define a dictionary as an environment variable in  a docker environment file, or otherwise. Googling isn't revealing anything helpful so far. Can you clarify how to do this?

**Comment by nbr23** [comment]
Hi @sanmadjack 
At this moment the easiest would be to not use environment variables, but use a custom `ydl_server/config.py` to set the variable.
If using docker-compose you could edit a local config.py with your options and then add something along those lines in your service:
```
    volumes:
      - ./config.py:/usr/src/app/ydl_server/config.py
```

I am not very satisfied with config management right now, so this should change soon.
Cheers
