### ISSUE TITLE
Support for different output folders

### ISSUE THREAD

**Issue by Fribb** [nbr23/youtube-dl-server#72]
My Workflow:

I use Flexget to monitor my Youtube Subscriptions through RSS feeds of the channels I am subscribed to. Flexget will check periodically for new videos and send those URLs to the youtube-dl-server docker container with `curl`. Those videos will be downloaded to the output directory specified in the `config.yml`. This output folder is watched by my Plex Media Server as a "youtube" library. Any new videos that are being added to the folder are scanned by plex and added to the library for playback through the Plex application.

This works well for everything Youtube-related.

The problem:

When I want to download videos that are not part of youtube or shouldn't be added to the default output folder. I would either have to download the video normally and then remove it from the folder after it was downloaded or use the CLI to specify the output directory manually.

Either of those ways works but is manual work.

My goal would be to be able to specify or override the output directory through the WebUI and the API so that I can be specific about where the video should be downloaded too.

For example, the API already allows a POST with existing parameters like `--data-urlencode "format=video/best"`. This could be expanded to do something like this  `--data-urlencode "output=/some/output/folder"`.

Having this as an option in the WebUI would be great as well.

**Comment by helmut72** [comment]
I currently have 4 instances of youtube-dl-server running with different FQDNs, which save in different folders because the content is different: Howto's (video), Fun (video), Music (audio), Podcast (video+audio)

It makes no sense to store podcasts in my music server, and vice versa, I don't need music for my podcast app.

Of course I can sort the files after downloading, but that's all manual work and time-consuming compared to a few bookmarklets, where I choose the most obvious one before downloading.

If this feature exists, I would only have to run one instance and save some RAM memory.

**Comment by nbr23** [comment]
Hi @Fribb , @helmut72 ,
You can now use [profiles](https://github.com/nbr23/youtube-dl-server?tab=readme-ov-file#profiles) for this! Let me know if you have any issues / this doesn't solve your need.
Cheers!

**Comment by helmut72** [comment]
Great, thanks! Now I need to know how a profile can be chosen in the bookmarklet? I have tried `format:`, `profile:` and `profiles:`, nothing works.

I only use a bookmarklet to add something to the queue. It's a one step compared to copy any url, switch to the tab of youtube-dl-server and paste the url.

**Comment by nbr23** [comment]
Yes sorry about that! Happy this works for you, thx!!

**Comment by Fribb** [comment]
Thanks, I just tried it and it works for me quite well. I will close the issue as completed.

**Comment by nbr23** [comment]
Amazing! Sorry it took 2 years to close this 😅
