### ISSUE TITLE
Adding Download-date column

### ISSUE THREAD

**Issue by blackerking** [nbr23/youtube-dl-server#75]
I share my youtube-DL App with some friends.
Suddenly some videos of mine are older than their.
So I have to "search" for them.

Is it possible to add a date of the download in the download list?
![grafik](https://user-images.githubusercontent.com/2019363/200570788-e45a4154-adb4-48b6-9208-93e1dbf789a3.png)

**Comment by nbr23** [comment]
hey @blackerking, not sure I follow what you are asking: we already have a Date column, what exactly are you looking to add ?

Thanks!

**Comment by blackerking** [comment]
The Date is the upload date, not the date of the download.
I would like to sort the files with their download-date.

**Comment by nbr23** [comment]
Ahh I see. I guess we could remove the upload date entirely and just show download date right? I can't see much use for the upload date itself...

I'll look into this, thx!

**Comment by nbr23** [comment]
Should be all good with https://github.com/nbr23/youtube-dl-server/commit/5fe00cb49952cb3f5396d94223d290a0acd25f68 ! Sorry for the long wait, let me know if you get any trouble with it.
Cheers!
