### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by Fribb** [nbr23/youtube-dl-server#78]
I am sure this is more of a yt-dlp issue but to document this here as well.

There is currently an issue with yt-dlp resulting in the following error message while trying to download a video.

> Unable to extract uploader id; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U

this also seems to be documented on the yt-dlp issue linked below.

https://github.com/yt-dlp/yt-dlp/issues/6253

So yt-dlp would need to be updated as soon as this has been fixed.

**Comment by nbr23** [comment]
Thx @Fribb they released [2023.02.17](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.02.17), I'm kicking a rebuild of the docker images and will close this once they're live.

**Comment by nbr23** [comment]
Alright images are live, thanks again!

**Comment by Fribb** [comment]
Thanks, that works.
