### ISSUE TITLE
ModuleNotFoundError: No module named 'starlette'  error

### ISSUE THREAD

**Issue by leo15dev** [nbr23/youtube-dl-server#80]
Traceback (most recent call last):
  File "/usr/src/app/./youtube-dl-server.py", line 2, in <module>
    from starlette.applications import Starlette
ModuleNotFoundError: No module named 'starlette'

the error occured after updated to  the latest youtube-dl-server/ yt-dlp docker images in this morring, thank you!

**Comment by nbr23** [comment]
Woops, looks like I broke it. Having a look, thanks!

**Comment by nbr23** [comment]
Alright, back in business with https://github.com/nbr23/youtube-dl-server/commit/202ceca9176246881177068dd077f06a84b57151, you can pull again the latest.
Thanks again for the report!
