### ISSUE TITLE
Remove failed download in log when retrying

### ISSUE THREAD

**Issue by Fribb** [nbr23/youtube-dl-server#82]
When you click on "Failed / Retry" the download is queued again and the server is trying to download the video again but the failed download stays in the log.

I think it would be a good idea to remove that failed download attempt from the list when you retry to download it. This would clean up the log from failed download attempts that were tried again and also finished. with multiple failed downloads, this would also make it easier to distinguish between videos you already have queued (since they are removed) and the remaining videos you still need to retry.

**Comment by nbr23** [comment]
Thanks, should be all set with https://github.com/nbr23/youtube-dl-server/commit/2f9af8ed7c06c8dbd09293c6828173d181484beb !
