### ISSUE TITLE
Permission denied for '/downloads' over a NFS Share

### ISSUE THREAD

**Issue by XxAcielxX** [nbr23/youtube-dl-server#83]
Hello,

I have recently moved Home Lab to a dedicated Machine where my Downloads directory is over a NFS Share mount. All the containers are working fine, except your `nbr23/youtube-dl-server:yt-dlp`.

Whenever I try to download something, it keeps saying
```
[download] Unable to open file: [Errno 13]
Permission denied: '/downloads/<filename>'
```
The user running the container has full Read/Write/Execute permissions to this NFS Share, but why does it say permission denied?

If I use a local directory, it works all good. Kindly help me out.

Regards

**Comment by nbr23** [comment]
Hey @XxAcielxX, looks like you might need to adjust either the permissions on your share, or use `--user` when running your container to have it run as a user with permissions on the share.
Cheers!

**Comment by XxAcielxX** [comment]
Yes, I have now set the `user: ${PUID}:${PGID}`, but I hope it won't break some other function where this user won't have access to root directories as mentioned in the other issue.
