### ISSUE TITLE
yt-dlp tag is broken

### ISSUE THREAD

**Issue by cron410** [nbr23/youtube-dl-server#85]
The issue is not present in the `yt-dlp_atomicparsely` tag so I am using that for now, reusing the same config and logs. 

I have these logs for a container created fresh from the `yt-dlp` tag:
```
Using configuration file /app_config/config.yml
Using yt-dlp module
Started download thread
Started jobs manager thread
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     10.1.1.139:39820 - "GET / HTTP/1.1" 304 Not Modified
INFO:     10.1.1.139:39820 - "GET /undefined/api/downloads/stats HTTP/1.1" 404 Not Found
INFO:     10.1.1.139:39822 - "GET /undefined/api/info HTTP/1.1" 404 Not Found
INFO:     10.1.1.139:39822 - "GET /undefined/api/extractors HTTP/1.1" 404 Not Found
INFO:     10.1.1.139:39822 - "GET /undefined/api/formats HTTP/1.1" 404 Not Found
INFO:     10.1.1.139:39822 - "GET /undefined/api/downloads HTTP/1.1" 404 Not Found
INFO:     10.1.1.139:39824 - "GET / HTTP/1.1" 304 Not Modified
INFO:     10.1.1.139:39824 - "GET /undefined/api/downloads/stats HTTP/1.1" 404 Not Found
INFO:     10.1.1.139:39828 - "GET /undefined/api/downloads HTTP/1.1" 404 Not Found
INFO:     10.1.1.139:39826 - "GET /undefined/api/info HTTP/1.1" 404 Not Found
```

The front page has no selector for video quality, and the Logs and Finished pages have no content for what I've already downloaded with the utility.

**Comment by cron410** [comment]
![Screen Shot 2023-03-27 at 4 39 46 PM](https://user-images.githubusercontent.com/3082899/228061219-ee5bc42d-e1e1-437d-989a-a9eb402f20d8.png)

![image](https://user-images.githubusercontent.com/3082899/228061514-1008facd-f864-4149-9640-1f80c7da63d2.png)

**Comment by nbr23** [comment]
The fix was pushed earlier today, so I think you just needed to pull the latest image.
Either way, I pushed a new fixed image now, so a docker pull should definitely fix it. If not please let met know!
Thanks!
