### ISSUE TITLE
Log page should use local time

### ISSUE THREAD

**Issue by fischy667** [nbr23/youtube-dl-server#87]
I use the line `-v /etc/localtime:/etc/localtime:ro \` to make the Alpine container use my local time, but the log page of youtube-dl-server does not use it and displays the time for GMT.

![grafik](https://user-images.githubusercontent.com/30476701/228874076-38af7005-7e52-46a9-bea0-311e461471f7.png)

**Comment by nbr23** [comment]
Thanks @fischy667 , I think we should be good with https://github.com/nbr23/youtube-dl-server/commit/58e14612c3a3ef77e31bd091661d308eb43d5acc, but let me know if it's still an issue.
Cheers!

**Comment by fischy667** [comment]
Works great for me. Thanks.
