### ISSUE TITLE
errors with subdomain / swag

### ISSUE THREAD

**Issue by blackerking** [nbr23/youtube-dl-server#88]
Hey,
lately I experienced some errors.
![grafik](https://user-images.githubusercontent.com/2019363/229747320-88963b5a-138b-4846-9772-4b283b141a02.png)

I think it is related with this commit:
https://github.com/nbr23/youtube-dl-server/commit/5015a561ba98ec1aceb79d425dd53fbd62e2c9dc#commitcomment-107456256

**Comment by blackerking** [comment]
I forgot to mention, the right path should be example.com/youtube-dl/assets/index.css

**Comment by nbr23** [comment]
hey @blackerking not sure I understand the issue. Are you running through docker, or natively?
Thx!

**Comment by nbr23** [comment]
Oh I see, thanks that's very useful! I pushed something but now that I re-read, I don't think it will fix it, it will only fix the issue for API endpoints. I need to look into the vue.js doc to see how to handle this best... stay tuned and sorry!

**Comment by nbr23** [comment]
Should be fixed now @blackerking. Let me know if not. Thanks!

**Comment by blackerking** [comment]
Works. Thank you.
