### ISSUE TITLE
"ERROR: ffmpeg exited with code 1" when using yt-dlp

### ISSUE THREAD

**Issue by Wado729** [nbr23/youtube-dl-server#91]
Using the docker image "nbr23/youtube-dl-server:yt-dlp" and trying to download a live stream such as Twitch, I receive the ERROR: ffmpeg exited with code 1 every time.  
I am using Portainer on my openmediavault NAS.

The site works fine when using the docker image nbr23/youtube-dl-server:latest

**Comment by nbr23** [comment]
Thanks, I will take a look! Do you have a link I can use to test this out?

**Comment by Wado729** [comment]
You can use any active Twitch link.

**Comment by nbr23** [comment]
Yep indeed, getting the same issue. I'm also getting it when just running yt-dlp natively on my laptop, so I think the issue is with yt-dlp itself... Don't think I can do much about it on my end, ffmpeg fails because the download itself fails

**Comment by nbr23** [comment]
Hmmm yeah sorry, something else is going on. I'm gonna keep looking!

**Comment by nbr23** [comment]
Ok I found the issue, fixed image should be live!
We'd gotten stuck on an old ffmpeg version as a result of this workaround here https://github.com/nbr23/youtube-dl-server/issues/67. It's not needed anymore, so I'm reverting that.

Let me know if that doesn't work. Thanks again!

**Comment by Wado729** [comment]
It works!  Great job, thanks!
