### ISSUE TITLE
[Feature Request] Add created_at filter to the api for http://192.168.50.37:48754/api/finished?

### ISSUE THREAD

**Issue by twist3dimages** [nbr23/youtube-dl-server#97]
It would be nice to have a date filter for the created_at part of the API like the one you created for show_logs so that I could filter finished downloads after a certain date (like past 24 hours)

for example 
http://192.168.50.37:48754/api/finished?created_after='2023-06-22'

referring to this part

    {
        "name": "test",
        "modified": "13:06 06/18/23",
        "created": "13:06 06/18/23",
        "size": null,
thanks!

**Comment by nbr23** [comment]
I look into this.
If you base your app on the API, beware that it's not that thought through and definitely subject to some cleaning up / changes in the future. I admit I didn't expect anyone to use it directly. I'll try to get it cleaned up and documented at some point :)

**Comment by twist3dimages** [comment]
Haha just having some fun trying to integrate it with something I'm building, thank you :)
