### ISSUE TITLE
[Feature Request] More Log functionality

### ISSUE THREAD

**Issue by Fribb** [nbr23/youtube-dl-server#98]
Here are a few features I would like to see in the Log list of downloaded items:

1. Filtering the list: This would allow us to filter for, for example, items that failed without having to scroll through the whole list. Clicking on the different tiles on the Stats on the top right could pre-filter the log history automatically. So, for example, I click on the red tile I directly get all items that failed in the log history
2. remove items from the log history: currently, I can only wait for "failed" downloads to be removed when I add another item that then throws the last item out of the list. With downloads that failed because I don't have access to them (like Youtube members), it would be good to remove that item from that list
3. just a visual thing I just noticed: the header is using the whole width of the screen but the table goes beyond that creating a horizontal scroll bar.

**Comment by nbr23** [comment]
3 should be fixed now. looking at the others!

For 2, I don't think I understood what you meant exactly, sorry!

**Comment by Fribb** [comment]
> For 2, I don't think I understood what you meant exactly, sorry!

just the ability to remove log history items manually.

**Comment by nbr23** [comment]
> > For 2, I don't think I understood what you meant exactly, sorry!
> 
> just the ability to remove log history items manually.

oh, to remove an individual line/entry in the logs?

**Comment by Fribb** [comment]
> oh, to remove an individual line/entry in the logs?

yes

**Comment by nbr23** [comment]
all set, thx!

**Comment by Fribb** [comment]
fantastic, thank you very much.

I had some trouble finding the delete button but after clicking the list item it showed at the bottom.
